language: c
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: bionic
      env:
      - BUILD_HOST_PARAMS=""
      - PREFIX="/usr"
script:
  - autoreconf -iv
  - ./configure --prefix=${PREFIX} ${BUILD_HOST_PARAMS}
  - make
  - sudo make install
