language: c
os: linux
dist: bionic

script:
  - autoreconf -iv
  - ./configure --prefix=${PREFIX} ${BUILD_HOST_PARAMS}
  - make
  - sudo make install

jobs:
  include:
    - stage: Tests
      name: "Linux"
      env:
      - BUILD_HOST_PARAMS=""
      - PREFIX="/usr"
    - name: "Windows cross-compiled"
      addons:
        apt:
          packages:
            - mingw-w64
      env:
      - BUILD_HOST_PARAMS="--host=x86_64-w64-mingw32"
      - PREFIX="/usr"

    - stage: Daily packages
      if: branch = master
      name: Launchpad - deb
      script: skip
      deploy:
        provider: launchpad
        slug: "~dciabrin/ngdevkit/+git/emudbg"
        oauth_token:
          secure: "HOv4v9b4s4NUHJguCwOz10ay6IFOYRxNQGiM+2ER1kLzv6RT4wV3rTODeEzYYS0YiqyPmsi02lR7jOS6xG++ufYu5grFwl4rcOC4xhDzSZ44X+xALzJMUrGswjoHxH6MiOz9KNdml3TKHaB+A8iSd+SNYNm7jYwYTyK2E1i88BTVzPaihqsSVUcHKW2bzH9qjsgGaPN9gFZnTdLqZYYBE0eEhnGEOmnFtK9pp8OFet7k+/b8fOQDl5mS3ICxpsE/5LMGU7vFSNls2Xt0+cQJLQnYfnsWDfN5k+quTmWgpkMc4i8+/n3mnUae1nLz7oTiK6k+ar5uETaD9fRYX/Kb977VK8m1NxuKP/egIVyVlA+tL7bFP5lDy0niEzn73Sr21PSDHcbGxgpcXCqyJL1RVs8hnyTdjFUdVElh5TPMUEYWF7kgWC92KLuDSfBCm3Ys+RQRliev+J2srBMPCETXC2saCz9xiAJUccuLbXZzzyWn1Ra3d7FrreRQADXsZ07GNQ1YhcDdKnRBIRxgYlUsbyC5lsKwN1KmlCYakVPuZLF1qxV/gczR97EWNV8QrMu6wuN5RkdKbtOGr4hjzOzwsDpSrJWpWb60MgKEojUMRSHZi5pp6CMudfLZGuoaEaUkBzmhdQy1xotv0UdSsQvffjep0E5OOL9bU8Q9hc83pM4="
        oauth_token_secret:
          secure: "TjIEjjnhRtNc7R5T70m4VWg1mxtYJ47NhQYP41BxVfpym5pSCupRcyRUaoWjSEDy8D3J/dxvJLqWwuDd6ZY/bzqy4yXdwtG25khFP/2PIVTeKSLmXG8dPfFrEBslOlNMx0QGkwrb8ZVczaqiMDWxJ4KMGXkY16gEyKNTuuyl/nXyXIpiAp/I+X2RCOKf6WIm0oqoyVT8V8xOkNxHFge+/jL+Xt9fZcjpFvM7oRuJTCA4UqS6uqJyt0fjyfvLCXJ4g9BmkytlWxQe73FXbJVieTeMqRl+M4W/PaVTwG0cPbghHtwG0mOCjnQreMK7P8IgX6To0ermCF/1UDz5TpWcGMbhUGSOiw1L+65G40JJOQeb5po9crLXMRLEyPDRIpry4hZjweiwqU9oVCjLy/01C9qZ6uKl2b2VhgtT02Zb+BChh1xMthHvWF6fFvCwVUKe3kcH8OwkfPx1+IZtqBv0WgE2x8/2vGurj8wn2b4offeziEm1RLs3dhmINpCJkVRxDqTFypiEVw/wOyie+zQNywqibXH2Ka4+oFS5ldWnOFQ9C72bf0SrluW0mh0YuDyIVApBApK4ZLjJK3NlSmFV1MTtM+/ZGIOJ/XLEM5JxyqxayPzTlx7WBMyepFSxHXxu7PPTGiyySe1wNrvdWOoDMicynCci36HVyMJjMDiOvn8="
