language: c
dist: bionic
matrix:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      env:
      - BUILD_HOST_PARAMS=""
      - PREFIX="/usr"
    - name: "Windows cross-compiled"
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - mingw-w64
      env:
      - BUILD_HOST_PARAMS="--host=x86_64-w64-mingw32"
      - PREFIX="/usr"

script:
  - autoreconf -iv
  - ./configure --prefix=${PREFIX} ${BUILD_HOST_PARAMS}
  - make
  - sudo make install

deploy:
  provider: launchpad
  slug: "~dciabrin/ngdevkit/+git/emudbg"
  oauth_token:
    secure: V1SwGDzk3e1vM7ZceFXW+TjLbalURVtPTLciJYAA/0WgH7zA+SnJ02xP3QejFtnBrDBnnyB48f3V17yyjYzmw9NrDYf11woRy+Ehy3dErb99AcXAFZepl+ez0tdnllOeTVmqZpLzI1Megtn19qNOUHaszojgYBXMBwSSMrD8FsD6JNd/ocIirTrbiX8nDf+Lpuq34W2Bqw4kaZXjCuQYDIeO+CRIFYiYzYYrjStF4gaHPi0rK8dGWO1LWiNC0e464mWXWlyyVDnZmwva6OQi1ZrnXB/Z5i/AJ97eSwaGM2RyL5zopRRaKGz8KElcJHq6uCz4RCvVw6GTTg4ZRQO5t2U//rLuBdZ30xHOjs7WpGfMdYLK+tN2rgK1o+KVP4ltnUC337g62dBlmPj9iHMyzrD5jIgxST8HklRTMLVaEUlI4DLT+jYSerJQBZ9zRBpoXCnRcvOre9rtQDtn+Q0uYHds9jgj1POJBUjdy/dktwOMqhonX7dSgCgVWB73zKTiC+XLXVHaUrfTsV4JIHpa4uxk31Em2aUCykM/AV65SWXqn7lCU0NeENAEALi3EbJ2Va8oVWd3ilsvBaNxw5bgIMw1GMb+ff7rMfsnGItRMziU1oj5sYTAPvMdWUrtQAR3TA6NuOIgi5F++i6SrhHDpad+WiElfIBcTANP7rK41MY=
  oauth_token_secret:
    secure: dkMIJbOJ3qUTDUWT/yOKUwSxmyjksKnWpA+GnGATAS68ycc6TmpTC+xn1WNPsQidatn+EdoebdnhpP76DeTqdix32KQ8MyFuWVeS4+ScOkE0F7125oMIrMX711QmtcxBXzyBp/95KAP+YPnIbpbqeMgxSntULCU+Xi4nr2E3EO6ExnfcF4YGiybyrqnY7tsnJD2MKoLOOGSPO7gUM4w/hKxUZZrKTQy5vDgYEDMBk0lMN2AbS5MyW1v72tmS52LlFi2jv/GMixENvtS7d/Fnjet/YTdq7meINW1AEqjUYnhGBMs8pWKdMDiXO7NOSFQvuBmAG9wQgylOM2dYDwsUgrxrj6437gBp9P7go1V/rc/OJXe5XkybUWt2ZwdmHWEQ7fh/YhAc50akGW3C51byXPT+mdB4v7PaNlwlGAuzCkmqqFNjEdw2e0/Ar4x5U3ozz7ocZXyJIRvew0s5VeAta1vzANhcEz2He6QCf8TXneL/egU30tqLqh4M4gO+z7QsYxL3zrIzxbw1hlm51tXPzK4oH2fPtzXX5x8S5W0xtu7yVpiERU/3yTJ6Wng1Pi9VI2JLQELeyO/EauvVevbQDOjZ+LBnwXVmfJOO0tNAqDA6ZQhhT5GblU1Ev7caQg2j+/YqQ/2r7LfqHz7xkaWoa1Vil7F4UElF0UfkXKvypf4=
