language: c
os: linux
dist: bionic

# Do not run on tag creation (e.g. skip tag created for nightly builds)
if: tag IS blank

env:
  global:
    - secure: "L9HvYDokIDBMdHg1lchFt4AeIPH5LTyadUTXtU+h6+faw19bv2lK182ln8MADISS9vnlnoX7qg0A7XaRU66TW6GLXpJfl14MswaUqB4+rdrpO0ZRfX0gbQ+wwAIqvYgWcV7mfK5Kq0kFoKaMMk4VTblmw7Z7Z8KiAt5tWHDiiqN69iK7OpVSbUCiUb2BvLYGlWEF1jMdvLYwlyzvxwCRti2p0UouBCV4cdbouF6sFUBNi1Y0BzZ9ZgwSZyTKuE3+Wyr9Z30LdDC1hdvRmPNh2u0oGZTe+oD745ka9YV2i5Oi+Laa39eQ5G/60TeDCMbaBfJTlpUaGFCeUMfOrOyoV5K0ZK4NqN0bpTzu/5P3BevyRmuPy0F8jAMWG8a1Y4QCJ5RBc5/vFhidlEqJ1gi+Af3EWjcE38dXCoZCWvCWr2I0EBQZsWDX17BAQZjje+T0pvGqaAe3woiu0mRdR33bvpHlIJ+skmmbU2CvY+4yxt8vKC9CRLNJ5H7Z6tebXsDrrfLNr4W3WFM2I/nKgxxnhh1uUny/60lAM9JCE2pEKqXgHagaHqw+PobV8L4v8xAuWTH4uLdQ7eSY4qkZkh4oAE9cAxZIBshF5HmtwON3E62nwLGSLfyQKfuKuD8nKuR0ioWtbKe48xsRvg00wZZCpf5/5MVQwV5qQ5WjIVOnEbE="

script:
  - autoreconf -iv
  - ./configure --prefix=${PREFIX} ${BUILD_HOST_PARAMS}
  - make
  - sudo make install

jobs:
  include:
    - stage: Tests
      name: "Linux"
      env:
      - BUILD_HOST_PARAMS=""
      - PREFIX="/usr"
    - name: "Windows cross-compiled"
      addons:
        apt:
          packages:
            - mingw-w64
      env:
      - BUILD_HOST_PARAMS="--host=x86_64-w64-mingw32"
      - PREFIX="/usr"

    - stage: Daily packages
      if: type = push AND branch = master
      name: Launchpad - deb
      script: skip
      deploy:
        provider: launchpad
        slug: "~dciabrin/ngdevkit/+git/emudbg"
        oauth_token:
          secure: "HOv4v9b4s4NUHJguCwOz10ay6IFOYRxNQGiM+2ER1kLzv6RT4wV3rTODeEzYYS0YiqyPmsi02lR7jOS6xG++ufYu5grFwl4rcOC4xhDzSZ44X+xALzJMUrGswjoHxH6MiOz9KNdml3TKHaB+A8iSd+SNYNm7jYwYTyK2E1i88BTVzPaihqsSVUcHKW2bzH9qjsgGaPN9gFZnTdLqZYYBE0eEhnGEOmnFtK9pp8OFet7k+/b8fOQDl5mS3ICxpsE/5LMGU7vFSNls2Xt0+cQJLQnYfnsWDfN5k+quTmWgpkMc4i8+/n3mnUae1nLz7oTiK6k+ar5uETaD9fRYX/Kb977VK8m1NxuKP/egIVyVlA+tL7bFP5lDy0niEzn73Sr21PSDHcbGxgpcXCqyJL1RVs8hnyTdjFUdVElh5TPMUEYWF7kgWC92KLuDSfBCm3Ys+RQRliev+J2srBMPCETXC2saCz9xiAJUccuLbXZzzyWn1Ra3d7FrreRQADXsZ07GNQ1YhcDdKnRBIRxgYlUsbyC5lsKwN1KmlCYakVPuZLF1qxV/gczR97EWNV8QrMu6wuN5RkdKbtOGr4hjzOzwsDpSrJWpWb60MgKEojUMRSHZi5pp6CMudfLZGuoaEaUkBzmhdQy1xotv0UdSsQvffjep0E5OOL9bU8Q9hc83pM4="
        oauth_token_secret:
          secure: "TjIEjjnhRtNc7R5T70m4VWg1mxtYJ47NhQYP41BxVfpym5pSCupRcyRUaoWjSEDy8D3J/dxvJLqWwuDd6ZY/bzqy4yXdwtG25khFP/2PIVTeKSLmXG8dPfFrEBslOlNMx0QGkwrb8ZVczaqiMDWxJ4KMGXkY16gEyKNTuuyl/nXyXIpiAp/I+X2RCOKf6WIm0oqoyVT8V8xOkNxHFge+/jL+Xt9fZcjpFvM7oRuJTCA4UqS6uqJyt0fjyfvLCXJ4g9BmkytlWxQe73FXbJVieTeMqRl+M4W/PaVTwG0cPbghHtwG0mOCjnQreMK7P8IgX6To0ermCF/1UDz5TpWcGMbhUGSOiw1L+65G40JJOQeb5po9crLXMRLEyPDRIpry4hZjweiwqU9oVCjLy/01C9qZ6uKl2b2VhgtT02Zb+BChh1xMthHvWF6fFvCwVUKe3kcH8OwkfPx1+IZtqBv0WgE2x8/2vGurj8wn2b4offeziEm1RLs3dhmINpCJkVRxDqTFypiEVw/wOyie+zQNywqibXH2Ka4+oFS5ldWnOFQ9C72bf0SrluW0mh0YuDyIVApBApK4ZLjJK3NlSmFV1MTtM+/ZGIOJ/XLEM5JxyqxayPzTlx7WBMyepFSxHXxu7PPTGiyySe1wNrvdWOoDMicynCci36HVyMJjMDiOvn8="

    - name: Homebrew - bottle
      if: type = push AND branch = master
      script:
        - git config --global user.name 'CI build bot'
        - git config --global user.email '<>'
        - git config --global url."https://api@github.com/".insteadOf "https://github.com/"
        - git clone https://github.com/dciabrin/homebrew-ngdevkit .travis/homebrew-ngdevkit
        - .travis/homebrew-ngdevkit/.travis/bump-project-nightly-build.sh emudbg

    - stage: Post-deploy
      name: Clean up old nightly tags
      addons:
        apt:
          packages:
            - jq
      script: .travis/gc-nightly-tags.sh --tag-regex='^refs/tags/nightly-[0-9]*'
      if: type = push AND branch = master
