language: c
os: linux
dist: bionic

script:
  - autoreconf -iv
  - ./configure --prefix=${PREFIX} ${BUILD_HOST_PARAMS}
  - make
  - sudo make install

jobs:
  include:
    - stage: Tests
      name: "Linux"
      env:
      - BUILD_HOST_PARAMS=""
      - PREFIX="/usr"
    - name: "Windows cross-compiled"
      addons:
        apt:
          packages:
            - mingw-w64
      env:
      - BUILD_HOST_PARAMS="--host=x86_64-w64-mingw32"
      - PREFIX="/usr"

    - stage: Daily packages
      if: branch = master
      name: Launchpad - deb
      script: skip
      deploy:
        provider: launchpad
        slug: "~dciabrin/ngdevkit/+git/emudbg"
        oauth_token:
          secure: "0ScYr2l0WFM1aaqfnpSG8nNNKiJ2TSurgoYS4tccBqqKXbBQj8HQi5P384wz0BI6uKTz5mSIZk9Su4J8TtjA+6b7LsCsyoe9PVBUWXdbdPIOrA7tHb7Rz5WzZ1dV7V7hKKSAURnPKC6MfYL7QOMnnGg9YtnBga+G+LFmd6Zhr2DlG2Yv9UVqgW4D6HAuKKWxYU9KVh9ECw26K8No8Ah+YhqGDP6rmP0tzW446JqpbkAUD+39aKL/znDr7RWaNVmnG2/SHJJLx3HKEEeAaSBoozvz0GxTIkSKImwU3j1II2we2qKiQubdxK9lWwNt/flwEJbFHknI2/uhD0wLc7Fyjcv5QV3LlNhA3xBct6I4PvSf6fzUHEpbHBDFt2u7shDekvPHjlGCbcDd57kd0TJRFInFuDTj2YTp13WNVQ92L7uczR12UD9ZEhiARnG3ydKYdXNDFR0oXTSxmOLyKnv3PnQljrio7YXD8ezTJCzKMBOfprvAn4SGMKzEBfxhwlqRneY1/ywqutVe4fmgd65Z4Fyu2jnRRI4vOtDUPiLxJMR/WpvJNul4IHhmHjqD+xjNkFnmA980fR5U9ZEv/ZXdSReNh0PhjZV9K5S4V2wBBpg7pdQoAoyz7eVBJrwHvo9nVD3W7kmWwkJPo+ZPWFGY5Ug766l7vRkkMmwIqSWhAN4="
        oauth_token_secret:
          secure: "OtiZxKgxD1ozisFg5TUi77lW2jC/p/dtHso/VVA6yRM3BICsmIexOfkB7eOiq+3P8awRy2E2zNoKT2dcro1ywHE4M5FTvKC5o8l7tOhZ/mv8+X0xs1lUFxhD+Qzxhk/0lu00sPRGKucgIF/XODtxlxv36N0S1ytRI4UNMVqcJ//2tjqmEcJwHltr83T51iezjnFPleyvmswPnP8aiXB2gyHHV7HRf9/bzQqDtEtfq2Tq3wrOX4YQcI9+QJWAsWrhexhWkLktDcZR0wiCWbsnXm3h8sxZbRF2lJmV5a+z5ZTqFL8gVe9xgEtwf8xxkSUuiTGLuNtfqPDcbbb4bUDOHWa9K6Zznpn9mk1zDkrUtKuA5ZTCOzX670HnxJvFPsJXm9i9qwGrHGomzft34BOFDte/3eoeibohfRxbDGA4p9yqLROPNyg5C7B47H5NmUJLzHx9ZQCqHDEN2EFDQHUqUE6Wq08tHaSS10KP/RpaX2TMkuiOVBs3Zda0ScOqp/hV3i+y/IT+4f1/sm7WW2CfSttrvcieMGo4drmK85QhGAiXhJu9zaD92dxFkuelxyQXhIcuB0kRZ9axxLXFbtLTh2UgX0paciL7YYdN1f/rOyGyMuFxTjl89UDqfd9wslpxuTKNCWwHp7CpJzxwtbJDNLOXN2ZVY15TM+XM5bJ+BnY="
